<server_start> = "server" "{"
<server_name> = "server_name" <string>
<listen> = "listen" <socket> | <port> | <host>
<root> = "root" <string>
<allow_methods> = "allow_methods" { <string> }
<autoindex> = "autoindex"  <string>
<index> = "index" { <string> }
<client_limit> = "client_body_limit" <number>
<error_pages> = "error_page"  { <number> }  <string>
<socket> = <host> , ":" , <port>
<host> = <number> , "." , <number> , "." , <number> , "." , <number>
<port> = <number>
<location> = "location" <location_modifier> <string> "{"
<location_modifier> = "="
<start> = "{"
<number> = { <digits> }
<digits> = ( "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" )
<end> = "}"
<string> =  <all_character>
<all_character> = ?all_visible_character_?